// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package model

import (
	"encoding/json"
	"fmt"
)

type ConnectorStopRequest struct {
	// The id of the connector to stop
	ConnectorId string `json:"connector_id" yaml:"connector_id" mapstructure:"connector_id"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ConnectorStopRequest) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["connector_id"]; raw != nil && !ok {
		return fmt.Errorf("field connector_id in ConnectorStopRequest: required")
	}
	type Plain ConnectorStopRequest
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ConnectorStopRequest(plain)
	return nil
}

type ConnectorStopResponse struct {
	// The instances of the connector that were started
	Instances []Instance `json:"instances" yaml:"instances" mapstructure:"instances"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ConnectorStopResponse) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["instances"]; raw != nil && !ok {
		return fmt.Errorf("field instances in ConnectorStopResponse: required")
	}
	type Plain ConnectorStopResponse
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ConnectorStopResponse(plain)
	return nil
}
