// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package model

type ConnectorListRequest map[string]interface{}

type ConnectorListResponse struct {
	// The available connectors
	Connectors []ConnectorSummary `json:"connectors,omitempty" yaml:"connectors,omitempty" mapstructure:"connectors,omitempty"`
}
