  version: '3'

  vars:
    SCP_URL: https://cloud.nas-test.synadia.io/api/core/beta
    ACCOUNT: 2lsqayf1NIFEvVwRdTXlAonrGbO

  includes:
    test: 'test/Taskfile.yml'

  tasks:
    clean:
      desc: Clean up the project
      cmds:
          - rm -rf target/*

    build:
      generates:
        - target/connect
      cmds:
        - go mod tidy
        - go build -o target/connect cmd/connect/*.go

    test:
      cmds:
        - task: test:run

    install:
      deps:
          - build
      cmds:
        - mkdir -p ~/.local/bin
        - cp target/connect ~/.local/bin/connect