  version: '3'

  vars:
    SCP_URL: https://cloud.nas-test.synadia.io/api/core/beta
    ACCOUNT: 2lsqayf1NIFEvVwRdTXlAonrGbO

  tasks:
    clean:
      desc: Clean up the project
      cmds:
          - rm -rf target/*

    test:
      cmds:
        - go run github.com/onsi/ginkgo/v2/ginkgo -r --compilers=4

    build:
      generates:
        - target/connect
      cmds:
        - go mod tidy
        - go build -o target/connect cmd/connect/*.go

    install:
      deps:
          - build
      cmds:
        - mkdir -p ~/.local/bin
        - cp target/connect ~/.local/bin/connect