// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package model

import "encoding/json"
import "fmt"

type ConnectorInstancesRequest struct {
	// The id of the connector to get instances for
	ConnectorId string `json:"connector_id" yaml:"connector_id" mapstructure:"connector_id"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ConnectorInstancesRequest) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["connector_id"]; raw != nil && !ok {
		return fmt.Errorf("field connector_id in ConnectorInstancesRequest: required")
	}
	type Plain ConnectorInstancesRequest
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ConnectorInstancesRequest(plain)
	return nil
}

type ConnectorInstancesResponse struct {
	// The instances of the connector
	Instances []Instance `json:"instances" yaml:"instances" mapstructure:"instances"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ConnectorInstancesResponse) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["instances"]; raw != nil && !ok {
		return fmt.Errorf("field instances in ConnectorInstancesResponse: required")
	}
	type Plain ConnectorInstancesResponse
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ConnectorInstancesResponse(plain)
	return nil
}
