// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package model

import "encoding/json"
import "fmt"

type ConnectorCreateRequest struct {
	// A description of the connector
	Description string `json:"description" yaml:"description" mapstructure:"description"`

	// The id of the connector to create
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// The connector runtime
	RuntimeId string `json:"runtime_id" yaml:"runtime_id" mapstructure:"runtime_id"`

	// Steps corresponds to the JSON schema field "steps".
	Steps Steps `json:"steps" yaml:"steps" mapstructure:"steps"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ConnectorCreateRequest) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["description"]; raw != nil && !ok {
		return fmt.Errorf("field description in ConnectorCreateRequest: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in ConnectorCreateRequest: required")
	}
	if _, ok := raw["runtime_id"]; raw != nil && !ok {
		return fmt.Errorf("field runtime_id in ConnectorCreateRequest: required")
	}
	if _, ok := raw["steps"]; raw != nil && !ok {
		return fmt.Errorf("field steps in ConnectorCreateRequest: required")
	}
	type Plain ConnectorCreateRequest
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ConnectorCreateRequest(plain)
	return nil
}

type ConnectorCreateResponse struct {
	// The created connector
	Connector Connector `json:"connector" yaml:"connector" mapstructure:"connector"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ConnectorCreateResponse) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["connector"]; raw != nil && !ok {
		return fmt.Errorf("field connector in ConnectorCreateResponse: required")
	}
	type Plain ConnectorCreateResponse
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ConnectorCreateResponse(plain)
	return nil
}
